# Generated by cpp11: do not edit by hand

hecfda_rng_sequence <- function(seed, n) {
  .Call(`_hecfdar_hecfda_rng_sequence`, seed, n)
}

hecfda_dist_eval <- function(type, params, method, x) {
  .Call(`_hecfdar_hecfda_dist_eval`, type, params, method, x)
}

hecfda_paired_f <- function(xs, ys, method, x) {
  .Call(`_hecfdar_hecfda_paired_f`, xs, ys, method, x)
}

hecfda_upd_sample_integrate <- function(xs, means, sds, seed) {
  .Call(`_hecfdar_hecfda_upd_sample_integrate`, xs, means, sds, seed)
}
