{
  "hash": "de1d0bea21bcfd99462dee8e41cf8afd",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Alternatives and benefits (Python)\"\nexecute:\n  enabled: true\n---\n\n::: {#5c152582 .cell execution_count=1}\n``` {.python .cell-code}\nimport hecfdapy as fda\nimport matplotlib.pyplot as plt\n\n```\n:::\n\n\n## The question\n\nIs a flood-risk project worth building? HEC-FDA answers with **equivalent annual damage (EqAD) reduced**: compute EqAD without the project, compute it again with the project, and subtract. This example builds both sides from the ground up -- a scenario, then an alternative, then the benefits comparison -- chaining `scenario_results()`, `alternative_ead()`, and `alternative_comparison()` exactly the way a real HEC-FDA study does.\n\n## The annualization math alone\n\nBefore chaining the whole pipeline, look at the annualization step by itself. `eqad()` takes an EAD at a base year and an EAD at a future year and folds them into one equivalent annual number:\n\n::: {#cdc93cdf .cell execution_count=2}\n``` {.python .cell-code}\nfda.eqad(35000, 2023, 50000, 2072, 50, 0.07)\n\n```\n\n::: {.cell-output .cell-output-display execution_count=2}\n```\n38835.309867432676\n```\n:::\n:::\n\n\nThat reproduces the upstream `ComputeEEAD_Test` oracle, `38835.31`. Three steps produce it:\n\n1. **Interpolate** -- linearly interpolate EAD between the base year and the most likely future year, one value per year of the analysis period. If the future year is reached before the period ends, every later year holds flat at the future value.\n2. **Discount** -- convert each year's EAD to present value at the given discount rate.\n3. **Annualize (PVIFA)** -- divide the summed present value by the present-value-interest-factor of an annuity over the period, turning a lump sum back into one equivalent annual payment.\n\nHere the base year is 2023, the future year is 2072, and the period of analysis is exactly 50 years -- so the future year lands on the last year of the period and every year gets interpolated, with no flat tail:\n\n::: {#3653ff1b .cell execution_count=3}\n``` {.python .cell-code}\nbase_value, base_year = 35000, 2023\nfuture_value, future_year = 50000, 2072\nperiod, rate = 50, 0.07\n\nyears = [base_year + i for i in range(period)]\ninterpolated = [base_value + (future_value - base_value) * i / (future_year - base_year)\n               for i in range(period)]\ndiscounted = [interpolated[i] / (1 + rate) ** (i + 1) for i in range(period)]\n\n```\n:::\n\n\n::: {#258117de .cell execution_count=4}\n``` {.python .cell-code}\nfig, ax = plt.subplots(figsize=(6, 4))\nax.plot(years, interpolated, color=\"#6b705c\", linewidth=2, label=\"interpolated EAD\")\nax.plot(years, discounted, color=\"#cb997e\", linewidth=2, label=\"discounted to present value\")\nax.set(xlabel=\"year\", ylabel=\"EAD ($)\")\nax.legend(frameon=False)\n\n```\n\n::: {.cell-output .cell-output-display}\n![](alternatives-py_files/figure-html/cell-5-output-1.png){width=536 height=356}\n:::\n:::\n\n\nSumming the discounted column and dividing by the annuity factor reproduces the same `38835.31` `eqad()` returned above:\n\n::: {#208632e1 .cell execution_count=5}\n``` {.python .cell-code}\npvifa = (1 - 1 / (1 + rate) ** period) / rate\nsum(discounted) / pvifa\n\n```\n\n::: {.cell-output .cell-output-display execution_count=5}\n```\n38835.30986743268\n```\n:::\n:::\n\n\n## Without-project alternative\n\nNow the full pipeline. A HEC-FDA alternative needs a base-year and a future-year scenario, each computed from an impact-area simulation the same way the EAD-simulation example did. This construct is the upstream `AlternativeResults_Test` case: a Uniform(0, 100000) flow frequency, a linear flow-stage curve from (0, 0) to (100000, 30), and a 3-point stage-damage curve. The future-year damages are exactly double the base-year damages -- the project has done nothing yet, so this is the without-project condition.\n\n::: {#30dff13a .cell execution_count=6}\n``` {.python .cell-code}\nwithout_base_sim = dict(\n    impact_area_id=1,\n    flow_frequency=dict(dist=\"Uniform\", params=[0, 100000, 1000]),\n    flow_stage=dict(x=[0, 100000], dist=\"Uniform\", params=[[0, 0, 10], [0, 30, 10]]),\n    stage_damage=[dict(\n        x=[0, 15, 30], dist=\"Uniform\",\n        params=[[0, 0, 10], [0, 600000, 1], [0, 600000, 1]],\n        damage_category=\"residential\", asset_category=\"structure\",\n    )],\n)\nwithout_future_sim = dict(without_base_sim, stage_damage=[dict(\n    without_base_sim[\"stage_damage\"][0],\n    params=[[0, 0, 10], [0, 1200000, 10], [0, 1200000, 10]],\n)])\n\n```\n:::\n\n\nRun each year through `scenario_results()`, then annualize both into one alternative with `alternative_ead()`:\n\n::: {#f7b57f40 .cell execution_count=7}\n``` {.python .cell-code}\nwithout_base = fda.scenario_results([without_base_sim], min_iterations=1, max_iterations=1,\n                                    deterministic=True)\nwithout_future = fda.scenario_results([without_future_sim], min_iterations=1, max_iterations=1,\n                                      deterministic=True)\n\nwithout = fda.alternative_ead(\n    without_base, without_future,\n    base_year=2023, future_year=2072, period_of_analysis=50, discount_rate=0.0275,\n    alternative_id=1,\n)\nwithout[\"mean_eqad\"], without[\"base_year_ead\"], without[\"future_year_ead\"]\n\n```\n\n::: {.cell-output .cell-output-display execution_count=7}\n```\n(208213.8040325943, 149999.99849999996, 299999.9969999999)\n```\n:::\n:::\n\n\nMean EqAD comes out to `208213.80`, the `AlternativeResults_Test` oracle for this exact construct (period 50, base year 2023, future year 2072, discount rate 2.75%), with a base-year EAD near 150000 and a future-year EAD near 300000 -- twice as much damage once the future-year curve takes over.\n\n## With-project alternative\n\nA project reduces damage. Here that project is a levee: 0% failure probability below stage 7.4999, 100% failure probability at 7.5 and above, sitting at a `top_of_levee_elevation` of 7.5. Everything else -- the flow frequency, the flow-stage curve, the stage-damage curve, the base/future years, discount rate, and period -- stays exactly the same as the without-project case:\n\n::: {#7ca31247 .cell execution_count=8}\n``` {.python .cell-code}\nlevee_spec = dict(\n    x=[0, 7.4999, 7.5], dist=\"Deterministic\", params=[[0], [0], [1]],\n    damage_category=\"residential\", asset_category=\"structure\",\n    top_of_levee_elevation=7.5,\n)\nwith_base_sim = dict(without_base_sim, levee=levee_spec)\nwith_future_sim = dict(without_future_sim, levee=levee_spec)\n\nwith_base = fda.scenario_results([with_base_sim], min_iterations=1, max_iterations=1,\n                                 deterministic=True)\nwith_future = fda.scenario_results([with_future_sim], min_iterations=1, max_iterations=1,\n                                   deterministic=True)\n\nwith_project = fda.alternative_ead(\n    with_base, with_future,\n    base_year=2023, future_year=2072, period_of_analysis=50, discount_rate=0.0275,\n    alternative_id=2,\n)\nwith_project[\"mean_eqad\"]\n\n```\n\n::: {.cell-output .cell-output-display execution_count=8}\n```\n161365.6976567101\n```\n:::\n:::\n\n\nMean EqAD drops to `161365.70` -- lower than the without-project `208213.80`, because the levee holds back damage below stage 7.5 in both the base and future year.\n\n## Benefits\n\nThe benefit of the project is the damage the levee prevents. `alternative_comparison()` subtracts the with-project alternative's damage distributions from the without-project alternative's and reports the reduction:\n\n::: {#0399e68c .cell execution_count=9}\n``` {.python .cell-code}\nbenefits = fda.alternative_comparison(without, with_project)\nbenefits[\"reduced\"]\n\n```\n\n::: {.cell-output .cell-output-display execution_count=9}\n```\n[{'alternative_id': 2,\n  'eqad_reduced': 46848.10637588418,\n  'base_year_ead_reduced': 33750.000000049986,\n  'future_year_ead_reduced': 67500.00000009997,\n  'with_project_eqad': 161365.6976567101}]\n```\n:::\n:::\n\n\nThe base-year EAD is reduced by `33750` and the future-year EAD by `67500` -- these are the `AlternativeComparisonReportShould`-style oracle values for this construct, and they are exactly what a levee holding back stages below 7.5 should prevent: a fixed share of both the base and future damage, scaled by how much of each curve sits under the levee's protection.\n\n## Single-use handles and validation\n\n`scenario_results()` and `alternative_ead()` both return a `\"handle\"` alongside their summary values. Each handle is **single-use**: `alternative_ead()` takes ownership of the scenario handles it is given, and `alternative_comparison()` takes ownership of the alternative handles it is given. A handle already consumed cannot be reused -- recompute the scenario or alternative if you need it again. That is why this example computes `without_base`/`without_future` and `with_base`/`with_future` as four separate scenario calls rather than trying to share one.\n\nNone of the numbers above are made up. `38835.31`, `208213.80`, `161365.70`, `33750`, and `67500` are the same literals the dotnet oracle gate (`make oracles`) checks against the real `HEC.FDA.Model.Alternative`/`AlternativeComparisonReport`, and this example chains `Scenario.Compute -> Alternative.AnnualizationCompute -> AlternativeComparisonReport.ComputeAlternativeComparisonReport` exactly the way the upstream `AlternativeComparisonReportShould`-style tests do -- the full stage-frequency -> stage-damage -> EAD -> EqAD -> benefits pipeline, validated end to end against the real HEC-FDA.\n\n",
    "supporting": [
      "alternatives-py_files"
    ],
    "filters": [],
    "includes": {}
  }
}