{
  "hash": "a1c953757dbaa9dd6b3ce4f98a1ba49d",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"EAD simulation (Python)\"\nexecute:\n  enabled: true\n---\n\n::: {#d3af1921 .cell execution_count=1}\n``` {.python .cell-code}\nimport hecfdapy as fda\nimport matplotlib.pyplot as plt\n\n```\n:::\n\n\n## The problem\n\nExpected annual damage (EAD) is HEC-FDA's core risk metric: expected dollar damage per year, integrated over every flood event weighted by how often it happens. The compute chains four pieces together:\n\n1. A **frequency curve** -- how often a flood of a given size occurs (an exceedance probability for each flow).\n2. A **flow-stage** (rating) curve -- converts flow to a water-surface stage.\n3. One or more **stage-damage curves** -- convert stage to dollar damage, per damage category and asset category.\n4. An **integration** step -- combines damage and frequency across the whole curve into EAD.\n\nEvery point on every curve can carry sampling uncertainty (a distribution instead of a fixed number). `ead_simulation()` runs this as a seeded Monte Carlo: draw once from each distribution, walk the four steps, accumulate the result into a histogram, repeat, report the mean. With `deterministic=True` and a single iteration, every distribution collapses to its mean instead of sampling, so what's left is the plain arithmetic of the pipeline with no Monte Carlo noise at all.\n\nThis is the same construct as the getting-started example, spelled out properly this time: a Uniform(0, 100000) flow frequency, a flow-stage line from (0, 0) to (100000, 30), and a stage-damage curve that is flat at 600000 for any stage of 15 or more.\n\n::: {#c914fcdf .cell execution_count=2}\n``` {.python .cell-code}\nsim = dict(\n    flow_frequency=dict(dist=\"Uniform\", params=[0, 100000, 1000]),\n    flow_stage=dict(x=[0, 100000], dist=\"Uniform\", params=[[0, 0, 10], [0, 30, 10]]),\n    stage_damage=[dict(\n        x=[0, 15, 30], dist=\"Uniform\",\n        params=[[0, 0, 10], [0, 600000, 10], [0, 600000, 10]],\n        damage_category=\"residential\", asset_category=\"Structure\",\n    )],\n)\n\nres = fda.ead_simulation(**sim, min_iterations=1, max_iterations=1, deterministic=True)\nres[\"total_ead\"], res[\"mean_aep\"]\n\n```\n\n::: {.cell-output .cell-output-display execution_count=2}\n```\n(149999.99849999996, 0.9505)\n```\n:::\n:::\n\n\n`res[\"total_ead\"]` is 150000 -- the HEC-FDA deterministic oracle for this construct. `res[\"mean_aep\"]` is the mean annual exceedance probability of the automatically-selected default performance threshold (HEC-FDA always derives one from the damage-frequency function itself, even with no threshold supplied): here it comes out to about 0.95, meaning this pipeline's own damage-producing range is exceeded in most years.\n\n## A levee\n\nA levee adds a **fragility curve**: the probability the levee fails, as a function of stage. Here the fragility is deterministic and binary -- 0% failure probability below stage 9.9999, 100% failure probability at stage 10 and above -- plus a `top_of_levee_elevation` marking where the levee itself sits.\n\n::: {#7e5ecc5f .cell execution_count=3}\n``` {.python .cell-code}\nsim_levee = dict(sim, levee=dict(\n    x=[0, 9.9999, 10], dist=\"Deterministic\", params=[[0], [0], [1]],\n    damage_category=\"residential\", asset_category=\"Structure\",\n    top_of_levee_elevation=100000,\n))\n\nres_levee = fda.ead_simulation(**sim_levee, min_iterations=1, max_iterations=1, deterministic=True)\nres_levee[\"total_ead\"]\n\n```\n\n::: {.cell-output .cell-output-display execution_count=3}\n```\n84187.49849999994\n```\n:::\n:::\n\n\nAdding the levee cuts expected annual damage from 150000 to 84187.50 -- HEC-FDA's own oracle for this exact construct. The levee doesn't erase damage: it only holds up to its own fragility curve, so above stage 10 damage still accrues at full risk. Below that, damage the base construct would have counted is now prevented.\n\n## The seeded Monte Carlo\n\nSwitch `deterministic` off and every distribution samples instead of collapsing to its mean. Each curve draws from HEC-FDA's own seeded generator with a fixed constant per curve type -- frequency 1234, flow-stage 3456, stage-damage 6789, and four more for interior/exterior stage, system response, and life loss -- ported exactly from the C# source. The exact sequence of draws, and so the exact result, is reproducible across runs, across languages, and against the real HEC-FDA.\n\nThe fixture this example reproduces also tags the flow-stage curve with the same damage and asset category as the stage-damage curve; the seeded compute's random-number setup needs that tag to line up (the deterministic pass above works without it):\n\n::: {#b0fd0638 .cell execution_count=4}\n``` {.python .cell-code}\nsim = dict(sim, flow_stage=dict(sim[\"flow_stage\"], damage_category=\"residential\",\n                                asset_category=\"Structure\"))\n\nres_100 = fda.ead_simulation(**sim, min_iterations=100, max_iterations=100, deterministic=False)\nres_100[\"total_ead\"]\n\n```\n\n::: {.cell-output .cell-output-display execution_count=4}\n```\n121194.5159789352\n```\n:::\n:::\n\n\nAt exactly 100 iterations this is `121194.5159789352` -- bit-for-bit the number the real HEC-FDA C# produces at the same iteration count, in both R and Python. That's the strongest check a Monte Carlo port can offer: not that two implementations land close together by chance, but that they draw the same sequence of random numbers and accumulate them the same way, all the way through the frequency -> stage -> damage -> integrate pipeline.\n\n## Convergence\n\nRun the same construct at increasing iteration counts and watch the seeded mean settle toward its own limit:\n\n::: {#4f0350fc .cell execution_count=5}\n``` {.python .cell-code}\niters = [100, 1000, 10000]\nmean_ead = []\nfor n in iters:\n    res_n = fda.ead_simulation(**sim, min_iterations=n, max_iterations=n, deterministic=False)\n    mean_ead.append(res_n[\"total_ead\"])\n\nlist(zip(iters, mean_ead))\n\n```\n\n::: {.cell-output .cell-output-display execution_count=5}\n```\n[(100, 121194.5159789352),\n (1000, 133985.40478349788),\n (10000, 135275.88477692605)]\n```\n:::\n:::\n\n\n::: {#668171ff .cell execution_count=6}\n``` {.python .cell-code}\nfig, ax = plt.subplots(figsize=(6, 4))\nax.plot(iters, mean_ead, color=\"#588157\", linewidth=2, marker=\"o\", label=\"seeded Monte Carlo\")\nax.axhline(150000, color=\"#cb997e\", linestyle=\"--\", linewidth=2, label=\"deterministic (150000, reference only)\")\nax.set_xscale(\"log\")\nax.set(xlabel=\"iterations\", ylabel=\"mean EAD ($)\")\nax.legend(frameon=False)\n\n```\n\n::: {.cell-output .cell-output-display}\n![](ead-simulation-py_files/figure-html/cell-7-output-1.png){width=545 height=359}\n:::\n:::\n\n\nThe sweep flattens near 135600, not 150000. That gap is not sampling noise, and more iterations will not close it. `deterministic=True` collapses every input distribution to its mean before any curve runs, so the deterministic pass evaluates the pipeline once on those mean values. The seeded Monte Carlo does the opposite: it samples first and evaluates the curves per draw, then averages the results. The stage-damage curve is nonlinear -- flat at 600000 for any stage of 15 or more -- so the mean of the damage is not the damage of the mean: `E[f(X)] != f(E[X])`. Averaging before a nonlinear curve and averaging after it are different questions with different correct answers. 150000 is the deterministic answer; the Monte Carlo converges to its own limit near 135600, and both are right.\n\n## Why the numbers are trustworthy\n\nNone of these values are made up. `150000`, `84187.50`, and `121194.5159789352` are the same literals the dotnet oracle gate (`make oracles`) checks against the real `HEC.FDA.Model.ImpactAreaScenarioSimulation.Compute`, and the last one is not just close: it is the exact value after exactly 100 iterations of the seeded Monte Carlo loop, reproduced bit-for-bit because the seven per-curve seed constants are ported exactly from the C# source, and every arithmetic step downstream of them matches too.\n\n",
    "supporting": [
      "ead-simulation-py_files"
    ],
    "filters": [],
    "includes": {}
  }
}