// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// glue.cpp
cpp11::doubles hecfda_rng_sequence(int seed, int n);
extern "C" SEXP _hecfdar_hecfda_rng_sequence(SEXP seed, SEXP n) {
  BEGIN_CPP11
    return cpp11::as_sexp(hecfda_rng_sequence(cpp11::as_cpp<cpp11::decay_t<int>>(seed), cpp11::as_cpp<cpp11::decay_t<int>>(n)));
  END_CPP11
}
// glue.cpp
double hecfda_dist_eval(std::string type, cpp11::doubles params, std::string method, double x);
extern "C" SEXP _hecfdar_hecfda_dist_eval(SEXP type, SEXP params, SEXP method, SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(hecfda_dist_eval(cpp11::as_cpp<cpp11::decay_t<std::string>>(type), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(params), cpp11::as_cpp<cpp11::decay_t<std::string>>(method), cpp11::as_cpp<cpp11::decay_t<double>>(x)));
  END_CPP11
}
// glue.cpp
double hecfda_paired_f(cpp11::doubles xs, cpp11::doubles ys, std::string method, double x);
extern "C" SEXP _hecfdar_hecfda_paired_f(SEXP xs, SEXP ys, SEXP method, SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(hecfda_paired_f(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(xs), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(ys), cpp11::as_cpp<cpp11::decay_t<std::string>>(method), cpp11::as_cpp<cpp11::decay_t<double>>(x)));
  END_CPP11
}
// glue.cpp
double hecfda_upd_sample_integrate(cpp11::doubles xs, cpp11::doubles means, cpp11::doubles sds, int seed);
extern "C" SEXP _hecfdar_hecfda_upd_sample_integrate(SEXP xs, SEXP means, SEXP sds, SEXP seed) {
  BEGIN_CPP11
    return cpp11::as_sexp(hecfda_upd_sample_integrate(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(xs), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(means), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(sds), cpp11::as_cpp<cpp11::decay_t<int>>(seed)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_hecfdar_hecfda_dist_eval",            (DL_FUNC) &_hecfdar_hecfda_dist_eval,            4},
    {"_hecfdar_hecfda_paired_f",             (DL_FUNC) &_hecfdar_hecfda_paired_f,             4},
    {"_hecfdar_hecfda_rng_sequence",         (DL_FUNC) &_hecfdar_hecfda_rng_sequence,         2},
    {"_hecfdar_hecfda_upd_sample_integrate", (DL_FUNC) &_hecfdar_hecfda_upd_sample_integrate, 4},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_hecfdar(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
