// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// glue.cpp
cpp11::doubles hecfda_rng_sequence(int seed, int n);
extern "C" SEXP _hecfdar_hecfda_rng_sequence(SEXP seed, SEXP n) {
  BEGIN_CPP11
    return cpp11::as_sexp(hecfda_rng_sequence(cpp11::as_cpp<cpp11::decay_t<int>>(seed), cpp11::as_cpp<cpp11::decay_t<int>>(n)));
  END_CPP11
}
// glue.cpp
double hecfda_dist_eval(std::string type, cpp11::doubles params, std::string method, double x);
extern "C" SEXP _hecfdar_hecfda_dist_eval(SEXP type, SEXP params, SEXP method, SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(hecfda_dist_eval(cpp11::as_cpp<cpp11::decay_t<std::string>>(type), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(params), cpp11::as_cpp<cpp11::decay_t<std::string>>(method), cpp11::as_cpp<cpp11::decay_t<double>>(x)));
  END_CPP11
}
// glue.cpp
double hecfda_paired_f(cpp11::doubles xs, cpp11::doubles ys, std::string method, double x);
extern "C" SEXP _hecfdar_hecfda_paired_f(SEXP xs, SEXP ys, SEXP method, SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(hecfda_paired_f(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(xs), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(ys), cpp11::as_cpp<cpp11::decay_t<std::string>>(method), cpp11::as_cpp<cpp11::decay_t<double>>(x)));
  END_CPP11
}
// glue.cpp
double hecfda_upd_sample_integrate(cpp11::doubles xs, cpp11::doubles means, cpp11::doubles sds, int seed);
extern "C" SEXP _hecfdar_hecfda_upd_sample_integrate(SEXP xs, SEXP means, SEXP sds, SEXP seed) {
  BEGIN_CPP11
    return cpp11::as_sexp(hecfda_upd_sample_integrate(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(xs), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(means), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(sds), cpp11::as_cpp<cpp11::decay_t<int>>(seed)));
  END_CPP11
}
// glue.cpp
double hecfda_value_uncertainty(std::string dist, double std_or_min, double max, std::string method, cpp11::doubles args);
extern "C" SEXP _hecfdar_hecfda_value_uncertainty(SEXP dist, SEXP std_or_min, SEXP max, SEXP method, SEXP args) {
  BEGIN_CPP11
    return cpp11::as_sexp(hecfda_value_uncertainty(cpp11::as_cpp<cpp11::decay_t<std::string>>(dist), cpp11::as_cpp<cpp11::decay_t<double>>(std_or_min), cpp11::as_cpp<cpp11::decay_t<double>>(max), cpp11::as_cpp<cpp11::decay_t<std::string>>(method), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(args)));
  END_CPP11
}
// glue.cpp
double hecfda_structure(std::string oc_name, std::string oc_damage_category, cpp11::doubles struct_depths, cpp11::strings struct_types, cpp11::list struct_params, cpp11::doubles content_depths, cpp11::strings content_types, cpp11::list content_params, std::string ffe_dist, double ffe_std_or_min, double ffe_max, std::string sv_dist, double sv_std_or_min, double sv_max, std::string csvr_dist, double csvr_std_or_min, double csvr_central, double csvr_max, int sample_iteration, bool sample_compute_is_deterministic, std::string fid, double first_floor_elevation, double val_struct, std::string st_damcat, std::string occtype, int impact_area_id, double val_cont, double val_vehic, double val_other, double ground_elevation, std::string method, double wse);
extern "C" SEXP _hecfdar_hecfda_structure(SEXP oc_name, SEXP oc_damage_category, SEXP struct_depths, SEXP struct_types, SEXP struct_params, SEXP content_depths, SEXP content_types, SEXP content_params, SEXP ffe_dist, SEXP ffe_std_or_min, SEXP ffe_max, SEXP sv_dist, SEXP sv_std_or_min, SEXP sv_max, SEXP csvr_dist, SEXP csvr_std_or_min, SEXP csvr_central, SEXP csvr_max, SEXP sample_iteration, SEXP sample_compute_is_deterministic, SEXP fid, SEXP first_floor_elevation, SEXP val_struct, SEXP st_damcat, SEXP occtype, SEXP impact_area_id, SEXP val_cont, SEXP val_vehic, SEXP val_other, SEXP ground_elevation, SEXP method, SEXP wse) {
  BEGIN_CPP11
    return cpp11::as_sexp(hecfda_structure(cpp11::as_cpp<cpp11::decay_t<std::string>>(oc_name), cpp11::as_cpp<cpp11::decay_t<std::string>>(oc_damage_category), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(struct_depths), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(struct_types), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(struct_params), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(content_depths), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(content_types), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(content_params), cpp11::as_cpp<cpp11::decay_t<std::string>>(ffe_dist), cpp11::as_cpp<cpp11::decay_t<double>>(ffe_std_or_min), cpp11::as_cpp<cpp11::decay_t<double>>(ffe_max), cpp11::as_cpp<cpp11::decay_t<std::string>>(sv_dist), cpp11::as_cpp<cpp11::decay_t<double>>(sv_std_or_min), cpp11::as_cpp<cpp11::decay_t<double>>(sv_max), cpp11::as_cpp<cpp11::decay_t<std::string>>(csvr_dist), cpp11::as_cpp<cpp11::decay_t<double>>(csvr_std_or_min), cpp11::as_cpp<cpp11::decay_t<double>>(csvr_central), cpp11::as_cpp<cpp11::decay_t<double>>(csvr_max), cpp11::as_cpp<cpp11::decay_t<int>>(sample_iteration), cpp11::as_cpp<cpp11::decay_t<bool>>(sample_compute_is_deterministic), cpp11::as_cpp<cpp11::decay_t<std::string>>(fid), cpp11::as_cpp<cpp11::decay_t<double>>(first_floor_elevation), cpp11::as_cpp<cpp11::decay_t<double>>(val_struct), cpp11::as_cpp<cpp11::decay_t<std::string>>(st_damcat), cpp11::as_cpp<cpp11::decay_t<std::string>>(occtype), cpp11::as_cpp<cpp11::decay_t<int>>(impact_area_id), cpp11::as_cpp<cpp11::decay_t<double>>(val_cont), cpp11::as_cpp<cpp11::decay_t<double>>(val_vehic), cpp11::as_cpp<cpp11::decay_t<double>>(val_other), cpp11::as_cpp<cpp11::decay_t<double>>(ground_elevation), cpp11::as_cpp<cpp11::decay_t<std::string>>(method), cpp11::as_cpp<cpp11::decay_t<double>>(wse)));
  END_CPP11
}
// glue.cpp
double hecfda_consequence_result(std::string damage_category, cpp11::list increments, std::string method, std::string compare_damage_category, cpp11::list compare_increments);
extern "C" SEXP _hecfdar_hecfda_consequence_result(SEXP damage_category, SEXP increments, SEXP method, SEXP compare_damage_category, SEXP compare_increments) {
  BEGIN_CPP11
    return cpp11::as_sexp(hecfda_consequence_result(cpp11::as_cpp<cpp11::decay_t<std::string>>(damage_category), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(increments), cpp11::as_cpp<cpp11::decay_t<std::string>>(method), cpp11::as_cpp<cpp11::decay_t<std::string>>(compare_damage_category), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(compare_increments)));
  END_CPP11
}
// glue.cpp
double hecfda_impact_area_stage_damage(int impact_area_id, std::string damage_category, std::string asset_category, double hydraulic_stage1, double hydraulic_stage2, bool use_reg_unreg, double stage);
extern "C" SEXP _hecfdar_hecfda_impact_area_stage_damage(SEXP impact_area_id, SEXP damage_category, SEXP asset_category, SEXP hydraulic_stage1, SEXP hydraulic_stage2, SEXP use_reg_unreg, SEXP stage) {
  BEGIN_CPP11
    return cpp11::as_sexp(hecfda_impact_area_stage_damage(cpp11::as_cpp<cpp11::decay_t<int>>(impact_area_id), cpp11::as_cpp<cpp11::decay_t<std::string>>(damage_category), cpp11::as_cpp<cpp11::decay_t<std::string>>(asset_category), cpp11::as_cpp<cpp11::decay_t<double>>(hydraulic_stage1), cpp11::as_cpp<cpp11::decay_t<double>>(hydraulic_stage2), cpp11::as_cpp<cpp11::decay_t<bool>>(use_reg_unreg), cpp11::as_cpp<cpp11::decay_t<double>>(stage)));
  END_CPP11
}
// glue.cpp
double hecfda_system_performance_results(int min_iterations, int max_iterations, double standard_probability, int master_seed, double threshold_value, int compute_chunks, std::string method);
extern "C" SEXP _hecfdar_hecfda_system_performance_results(SEXP min_iterations, SEXP max_iterations, SEXP standard_probability, SEXP master_seed, SEXP threshold_value, SEXP compute_chunks, SEXP method) {
  BEGIN_CPP11
    return cpp11::as_sexp(hecfda_system_performance_results(cpp11::as_cpp<cpp11::decay_t<int>>(min_iterations), cpp11::as_cpp<cpp11::decay_t<int>>(max_iterations), cpp11::as_cpp<cpp11::decay_t<double>>(standard_probability), cpp11::as_cpp<cpp11::decay_t<int>>(master_seed), cpp11::as_cpp<cpp11::decay_t<double>>(threshold_value), cpp11::as_cpp<cpp11::decay_t<int>>(compute_chunks), cpp11::as_cpp<cpp11::decay_t<std::string>>(method)));
  END_CPP11
}
// glue.cpp
double hecfda_impact_area_scenario_simulation(int impact_area_id, std::string flow_freq_type, cpp11::doubles flow_freq_params, cpp11::doubles flow_stage_xs, cpp11::strings flow_stage_types, cpp11::list flow_stage_params, cpp11::doubles stage_damage_xs, cpp11::strings stage_damage_types, cpp11::list stage_damage_params, std::string damage_category, std::string asset_category, int threshold_id, double threshold_value, int min_iterations, int max_iterations, bool compute_is_deterministic);
extern "C" SEXP _hecfdar_hecfda_impact_area_scenario_simulation(SEXP impact_area_id, SEXP flow_freq_type, SEXP flow_freq_params, SEXP flow_stage_xs, SEXP flow_stage_types, SEXP flow_stage_params, SEXP stage_damage_xs, SEXP stage_damage_types, SEXP stage_damage_params, SEXP damage_category, SEXP asset_category, SEXP threshold_id, SEXP threshold_value, SEXP min_iterations, SEXP max_iterations, SEXP compute_is_deterministic) {
  BEGIN_CPP11
    return cpp11::as_sexp(hecfda_impact_area_scenario_simulation(cpp11::as_cpp<cpp11::decay_t<int>>(impact_area_id), cpp11::as_cpp<cpp11::decay_t<std::string>>(flow_freq_type), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(flow_freq_params), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(flow_stage_xs), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(flow_stage_types), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(flow_stage_params), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(stage_damage_xs), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(stage_damage_types), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(stage_damage_params), cpp11::as_cpp<cpp11::decay_t<std::string>>(damage_category), cpp11::as_cpp<cpp11::decay_t<std::string>>(asset_category), cpp11::as_cpp<cpp11::decay_t<int>>(threshold_id), cpp11::as_cpp<cpp11::decay_t<double>>(threshold_value), cpp11::as_cpp<cpp11::decay_t<int>>(min_iterations), cpp11::as_cpp<cpp11::decay_t<int>>(max_iterations), cpp11::as_cpp<cpp11::decay_t<bool>>(compute_is_deterministic)));
  END_CPP11
}
// glue.cpp
double hecfda_alternative_compute_eqad(double base_value, int base_year, double future_value, int future_year, int period_of_analysis, double discount_rate);
extern "C" SEXP _hecfdar_hecfda_alternative_compute_eqad(SEXP base_value, SEXP base_year, SEXP future_value, SEXP future_year, SEXP period_of_analysis, SEXP discount_rate) {
  BEGIN_CPP11
    return cpp11::as_sexp(hecfda_alternative_compute_eqad(cpp11::as_cpp<cpp11::decay_t<double>>(base_value), cpp11::as_cpp<cpp11::decay_t<int>>(base_year), cpp11::as_cpp<cpp11::decay_t<double>>(future_value), cpp11::as_cpp<cpp11::decay_t<int>>(future_year), cpp11::as_cpp<cpp11::decay_t<int>>(period_of_analysis), cpp11::as_cpp<cpp11::decay_t<double>>(discount_rate)));
  END_CPP11
}
// glue.cpp
double hecfda_scenario(cpp11::integers impact_area_ids, std::string flow_freq_type, cpp11::doubles flow_freq_params, cpp11::doubles flow_stage_xs, cpp11::strings flow_stage_types, cpp11::list flow_stage_params, cpp11::doubles stage_damage_xs, cpp11::strings stage_damage_types, cpp11::list stage_damage_params, std::string damage_category, std::string asset_category, int threshold_id, double threshold_value, int min_iterations, int max_iterations, bool compute_is_deterministic, int query_impact_area_id);
extern "C" SEXP _hecfdar_hecfda_scenario(SEXP impact_area_ids, SEXP flow_freq_type, SEXP flow_freq_params, SEXP flow_stage_xs, SEXP flow_stage_types, SEXP flow_stage_params, SEXP stage_damage_xs, SEXP stage_damage_types, SEXP stage_damage_params, SEXP damage_category, SEXP asset_category, SEXP threshold_id, SEXP threshold_value, SEXP min_iterations, SEXP max_iterations, SEXP compute_is_deterministic, SEXP query_impact_area_id) {
  BEGIN_CPP11
    return cpp11::as_sexp(hecfda_scenario(cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(impact_area_ids), cpp11::as_cpp<cpp11::decay_t<std::string>>(flow_freq_type), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(flow_freq_params), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(flow_stage_xs), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(flow_stage_types), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(flow_stage_params), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(stage_damage_xs), cpp11::as_cpp<cpp11::decay_t<cpp11::strings>>(stage_damage_types), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(stage_damage_params), cpp11::as_cpp<cpp11::decay_t<std::string>>(damage_category), cpp11::as_cpp<cpp11::decay_t<std::string>>(asset_category), cpp11::as_cpp<cpp11::decay_t<int>>(threshold_id), cpp11::as_cpp<cpp11::decay_t<double>>(threshold_value), cpp11::as_cpp<cpp11::decay_t<int>>(min_iterations), cpp11::as_cpp<cpp11::decay_t<int>>(max_iterations), cpp11::as_cpp<cpp11::decay_t<bool>>(compute_is_deterministic), cpp11::as_cpp<cpp11::decay_t<int>>(query_impact_area_id)));
  END_CPP11
}
// glue.cpp
cpp11::doubles hecfda_dist_sample(std::string type, cpp11::doubles params, int n, int seed);
extern "C" SEXP _hecfdar_hecfda_dist_sample(SEXP type, SEXP params, SEXP n, SEXP seed) {
  BEGIN_CPP11
    return cpp11::as_sexp(hecfda_dist_sample(cpp11::as_cpp<cpp11::decay_t<std::string>>(type), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(params), cpp11::as_cpp<cpp11::decay_t<int>>(n), cpp11::as_cpp<cpp11::decay_t<int>>(seed)));
  END_CPP11
}
// glue.cpp
cpp11::list hecfda_ead_simulation(cpp11::list spec, int min_iterations, int max_iterations, bool compute_is_deterministic);
extern "C" SEXP _hecfdar_hecfda_ead_simulation(SEXP spec, SEXP min_iterations, SEXP max_iterations, SEXP compute_is_deterministic) {
  BEGIN_CPP11
    return cpp11::as_sexp(hecfda_ead_simulation(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(spec), cpp11::as_cpp<cpp11::decay_t<int>>(min_iterations), cpp11::as_cpp<cpp11::decay_t<int>>(max_iterations), cpp11::as_cpp<cpp11::decay_t<bool>>(compute_is_deterministic)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_hecfdar_hecfda_alternative_compute_eqad",        (DL_FUNC) &_hecfdar_hecfda_alternative_compute_eqad,         6},
    {"_hecfdar_hecfda_consequence_result",              (DL_FUNC) &_hecfdar_hecfda_consequence_result,               5},
    {"_hecfdar_hecfda_dist_eval",                       (DL_FUNC) &_hecfdar_hecfda_dist_eval,                        4},
    {"_hecfdar_hecfda_dist_sample",                     (DL_FUNC) &_hecfdar_hecfda_dist_sample,                      4},
    {"_hecfdar_hecfda_ead_simulation",                  (DL_FUNC) &_hecfdar_hecfda_ead_simulation,                   4},
    {"_hecfdar_hecfda_impact_area_scenario_simulation", (DL_FUNC) &_hecfdar_hecfda_impact_area_scenario_simulation, 16},
    {"_hecfdar_hecfda_impact_area_stage_damage",        (DL_FUNC) &_hecfdar_hecfda_impact_area_stage_damage,         7},
    {"_hecfdar_hecfda_paired_f",                        (DL_FUNC) &_hecfdar_hecfda_paired_f,                         4},
    {"_hecfdar_hecfda_rng_sequence",                    (DL_FUNC) &_hecfdar_hecfda_rng_sequence,                     2},
    {"_hecfdar_hecfda_scenario",                        (DL_FUNC) &_hecfdar_hecfda_scenario,                        17},
    {"_hecfdar_hecfda_structure",                       (DL_FUNC) &_hecfdar_hecfda_structure,                       32},
    {"_hecfdar_hecfda_system_performance_results",      (DL_FUNC) &_hecfdar_hecfda_system_performance_results,       7},
    {"_hecfdar_hecfda_upd_sample_integrate",            (DL_FUNC) &_hecfdar_hecfda_upd_sample_integrate,             4},
    {"_hecfdar_hecfda_value_uncertainty",               (DL_FUNC) &_hecfdar_hecfda_value_uncertainty,                5},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_hecfdar(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
